





//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets63BDE988589C96BFC21322DD2FEE34E46F889AE2535299FAE7499AFE376BE0A8))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    [System.Diagnostics.DebuggerNonUserCode()][System.CodeDom.Compiler.GeneratedCode("EF","v 4.0")]public sealed class ViewsForBaseEntitySets63BDE988589C96BFC21322DD2FEE34E46F889AE2535299FAE7499AFE376BE0A8 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets63BDE988589C96BFC21322DD2FEE34E46F889AE2535299FAE7499AFE376BE0A8()
        {
            this.EdmEntityContainerName = "DemoEntities";
            this.StoreEntityContainerName = "TelChinaTRFDemoDomainModelStoreContainer";
            this.HashOverMappingClosure = "6f6c99d57b23174898107667442a303059b9a57b1630d20c797d15dd4a5515b2";
            this.HashOverAllExtentViews = "d87e16b2222d536017fc588ac85401462dcb4dece071f1af239a99685141c51c";
            this.ViewCount = 18;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.SysParam
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.SysParam", @"
    SELECT VALUE -- Constructing SysParam
        [TelChina.TRF.Demo.DomainModel.Store.SysParam](T1.SysParam_sysparamid, T1.SysParam_sysparamName, T1.SysParam_sysparamDsc, T1.SysParam_sysparamValue, T1.SysParam_SysVersion)
    FROM (
        SELECT 
            T.sysparamid AS SysParam_sysparamid, 
            T.sysparamName AS SysParam_sysparamName, 
            T.sysparamDsc AS SysParam_sysparamDsc, 
            T.sysparamValue AS SysParam_sysparamValue, 
            T.SysVersion AS SysParam_SysVersion, 
            True AS _from0
        FROM DemoEntities.SysParam AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.SysParam
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.SysParam", @"
    SELECT VALUE -- Constructing SysParam
        [TelChina.TRF.Demo.DomainModel.SysParam](T1.SysParam_sysparamid, T1.SysParam_sysparamName, T1.SysParam_sysparamDsc, T1.SysParam_sysparamValue, T1.SysParam_SysVersion)
    FROM (
        SELECT 
            T.sysparamid AS SysParam_sysparamid, 
            T.sysparamName AS SysParam_sysparamName, 
            T.sysparamDsc AS SysParam_sysparamDsc, 
            T.sysparamValue AS SysParam_sysparamValue, 
            T.SysVersion AS SysParam_SysVersion, 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.SysParam AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.OrderSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.OrderSet", @"
    SELECT VALUE -- Constructing OrderSet
        [TelChina.TRF.Demo.DomainModel.Store.OrderSet](T1.OrderSet_Id, T1.OrderSet_DocNo, T1.OrderSet_CreatedOn, T1.OrderSet_CreatedBy, T1.OrderSet_SysVersion, T1.OrderSet_ModifiedBy, T1.OrderSet_ModifiedOn)
    FROM (
        SELECT 
            T.Id AS OrderSet_Id, 
            T.DocNo AS OrderSet_DocNo, 
            T.CreatedOn AS OrderSet_CreatedOn, 
            T.CreatedBy AS OrderSet_CreatedBy, 
            T.SysVersion AS OrderSet_SysVersion, 
            T.ModifiedBy AS OrderSet_ModifiedBy, 
            T.ModifiedOn AS OrderSet_ModifiedOn, 
            True AS _from0
        FROM DemoEntities.OrderSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.OrderSet_MO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.OrderSet_MO", @"
    SELECT VALUE -- Constructing OrderSet_MO
        [TelChina.TRF.Demo.DomainModel.Store.OrderSet_MO](T1.[OrderSet_MO.Product], T1.[OrderSet_MO.Id])
    FROM (
        SELECT 
            TREAT(T AS [TelChina.TRF.Demo.DomainModel.MO]).Product AS [OrderSet_MO.Product], 
            T.Id AS [OrderSet_MO.Id], 
            True AS _from0
        FROM DemoEntities.OrderSet AS T
        WHERE T IS OF (ONLY [TelChina.TRF.Demo.DomainModel.MO])
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.OrderSet_SO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.OrderSet_SO", @"
    SELECT VALUE -- Constructing OrderSet_SO
        [TelChina.TRF.Demo.DomainModel.Store.OrderSet_SO](T1.[OrderSet_SO.Customer], T1.[OrderSet_SO.Id])
    FROM (
        SELECT 
            TREAT(T AS [TelChina.TRF.Demo.DomainModel.SO]).Customer AS [OrderSet_SO.Customer], 
            T.Id AS [OrderSet_SO.Id], 
            True AS _from0
        FROM DemoEntities.OrderSet AS T
        WHERE T IS OF (ONLY [TelChina.TRF.Demo.DomainModel.SO])
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.OrderLineSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.OrderLineSet", @"
    SELECT VALUE -- Constructing OrderLineSet
        [TelChina.TRF.Demo.DomainModel.Store.OrderLineSet](T1.OrderLineSet_Id, T1.OrderLineSet_Detail, T1.OrderLineSet_OrderId, T1.OrderLineSet_LineNum, T1.OrderLineSet_SysVersion)
    FROM (
        SELECT 
            T.Id AS OrderLineSet_Id, 
            T.Detail AS OrderLineSet_Detail, 
            T.OrderId AS OrderLineSet_OrderId, 
            T.LineNum AS OrderLineSet_LineNum, 
            T.SysVersion AS OrderLineSet_SysVersion, 
            True AS _from0
        FROM DemoEntities.OrderLineSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.PickSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.PickSet", @"
    SELECT VALUE -- Constructing PickSet
        [TelChina.TRF.Demo.DomainModel.Store.PickSet](T1.PickSet_Id, T1.PickSet_Code, T1.PickSet_CreatedOn, T1.PickSet_CreatedBy, T1.PickSet_SysVersion, T1.PickSet_ModifiedBy, T1.PickSet_ModifiedOn, T1.PickSet_Name, T1.PickSet_MOId)
    FROM (
        SELECT 
            T.Id AS PickSet_Id, 
            T.Code AS PickSet_Code, 
            T.CreatedOn AS PickSet_CreatedOn, 
            T.CreatedBy AS PickSet_CreatedBy, 
            T.SysVersion AS PickSet_SysVersion, 
            T.ModifiedBy AS PickSet_ModifiedBy, 
            T.ModifiedOn AS PickSet_ModifiedOn, 
            T.Name AS PickSet_Name, 
            T.MOId AS PickSet_MOId, 
            True AS _from0
        FROM DemoEntities.PickSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.OrderSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.OrderSet", "\r\n    SELECT VALUE -- Constructing OrderSet\r\n        CASE\r\n            WHEN T5._f" +
                    "rom1 THEN [TelChina.TRF.Demo.DomainModel.MO](T5.Order_Id, T5.Order_DocNo, T5.Ord" +
                    "er_CreatedOn, T5.Order_CreatedBy, T5.Order_SysVersion, T5.Order_ModifiedBy, T5.O" +
                    "rder_ModifiedOn, T5.MO_Product)\r\n            ELSE [TelChina.TRF.Demo.DomainModel" +
                    ".SO](T5.Order_Id, T5.Order_DocNo, T5.Order_CreatedOn, T5.Order_CreatedBy, T5.Ord" +
                    "er_SysVersion, T5.Order_ModifiedBy, T5.Order_ModifiedOn, T5.SO_Customer)\r\n      " +
                    "  END\r\n    FROM (\r\n        SELECT T3.Order_Id, T4.Order_DocNo, T4.Order_CreatedO" +
                    "n, T4.Order_CreatedBy, T4.Order_SysVersion, T4.Order_ModifiedBy, T4.Order_Modifi" +
                    "edOn, T3.MO_Product, T3.SO_Customer, T4._from0, T3._from1, T3._from2\r\n        FR" +
                    "OM  ( (\r\n                SELECT \r\n                    T.Id AS Order_Id, \r\n      " +
                    "              T.Product AS MO_Product, \r\n                    CAST(NULL AS [Edm.S" +
                    "tring]) AS SO_Customer, \r\n                    True AS _from1, \r\n                " +
                    "    False AS _from2\r\n                FROM TelChinaTRFDemoDomainModelStoreContain" +
                    "er.OrderSet_MO AS T)\r\n                UNION ALL (\r\n                SELECT \r\n    " +
                    "                T.Id AS Order_Id, \r\n                    CAST(NULL AS [Edm.String" +
                    "]) AS MO_Product, \r\n                    T.Customer AS SO_Customer, \r\n           " +
                    "         False AS _from1, \r\n                    True AS _from2\r\n                " +
                    "FROM TelChinaTRFDemoDomainModelStoreContainer.OrderSet_SO AS T)) AS T3\r\n        " +
                    "    INNER JOIN (\r\n            SELECT \r\n                T.Id AS Order_Id, \r\n     " +
                    "           T.DocNo AS Order_DocNo, \r\n                T.CreatedOn AS Order_Create" +
                    "dOn, \r\n                T.CreatedBy AS Order_CreatedBy, \r\n                T.SysVe" +
                    "rsion AS Order_SysVersion, \r\n                T.ModifiedBy AS Order_ModifiedBy, \r" +
                    "\n                T.ModifiedOn AS Order_ModifiedOn, \r\n                True AS _fr" +
                    "om0\r\n            FROM TelChinaTRFDemoDomainModelStoreContainer.OrderSet AS T) AS" +
                    " T4\r\n            ON T3.Order_Id = T4.Order_Id\r\n    ) AS T5");
        }
        
        /// <Summary>
        /// return view for DemoEntities.OrderLineSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.OrderLineSet", @"
    SELECT VALUE -- Constructing OrderLineSet
        [TelChina.TRF.Demo.DomainModel.OrderLine](T1.OrderLine_Id, T1.OrderLine_Detail, T1.OrderLine_OrderId, T1.OrderLine_LineNum, T1.OrderLine_SysVersion)
    FROM (
        SELECT 
            T.Id AS OrderLine_Id, 
            T.Detail AS OrderLine_Detail, 
            T.OrderId AS OrderLine_OrderId, 
            T.LineNum AS OrderLine_LineNum, 
            T.SysVersion AS OrderLine_SysVersion, 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.OrderLineSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.PickSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.PickSet", @"
    SELECT VALUE -- Constructing PickSet
        [TelChina.TRF.Demo.DomainModel.Pick](T1.Pick_Id, T1.Pick_Code, T1.Pick_CreatedOn, T1.Pick_CreatedBy, T1.Pick_SysVersion, T1.Pick_ModifiedBy, T1.Pick_ModifiedOn, T1.Pick_Name, T1.Pick_MOId)
    FROM (
        SELECT 
            T.Id AS Pick_Id, 
            T.Code AS Pick_Code, 
            T.CreatedOn AS Pick_CreatedOn, 
            T.CreatedBy AS Pick_CreatedBy, 
            T.SysVersion AS Pick_SysVersion, 
            T.ModifiedBy AS Pick_ModifiedBy, 
            T.ModifiedOn AS Pick_ModifiedOn, 
            T.Name AS Pick_Name, 
            T.MOId AS Pick_MOId, 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.PickSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.UserSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.UserSet", @"
    SELECT VALUE -- Constructing UserSet
        [TelChina.TRF.Demo.DomainModel.Store.UserSet](T1.UserSet_Id, T1.UserSet_Code, T1.UserSet_CreatedOn, T1.UserSet_CreatedBy, T1.UserSet_SysVersion, T1.UserSet_ModifiedBy, T1.UserSet_ModifiedOn, T1.UserSet_Name)
    FROM (
        SELECT 
            T.Id AS UserSet_Id, 
            T.Code AS UserSet_Code, 
            T.CreatedOn AS UserSet_CreatedOn, 
            T.CreatedBy AS UserSet_CreatedBy, 
            T.SysVersion AS UserSet_SysVersion, 
            T.ModifiedBy AS UserSet_ModifiedBy, 
            T.ModifiedOn AS UserSet_ModifiedOn, 
            T.Name AS UserSet_Name, 
            True AS _from0
        FROM DemoEntities.UserSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.RoleSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.RoleSet", @"
    SELECT VALUE -- Constructing RoleSet
        [TelChina.TRF.Demo.DomainModel.Store.RoleSet](T1.RoleSet_Id, T1.RoleSet_Code, T1.RoleSet_CreatedOn, T1.RoleSet_CreatedBy, T1.RoleSet_SysVersion, T1.RoleSet_ModifiedBy, T1.RoleSet_ModifiedOn, T1.RoleSet_Name)
    FROM (
        SELECT 
            T.Id AS RoleSet_Id, 
            T.Code AS RoleSet_Code, 
            T.CreatedOn AS RoleSet_CreatedOn, 
            T.CreatedBy AS RoleSet_CreatedBy, 
            T.SysVersion AS RoleSet_SysVersion, 
            T.ModifiedBy AS RoleSet_ModifiedBy, 
            T.ModifiedOn AS RoleSet_ModifiedOn, 
            T.Name AS RoleSet_Name, 
            True AS _from0
        FROM DemoEntities.RoleSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.UserRoleSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.UserRoleSet", @"
    SELECT VALUE -- Constructing UserRoleSet
        [TelChina.TRF.Demo.DomainModel.Store.UserRoleSet](T1.UserRoleSet_Id, T1.UserRoleSet_CreatedOn, T1.UserRoleSet_CreatedBy, T1.UserRoleSet_SysVersion, T1.UserRoleSet_ModifiedBy, T1.UserRoleSet_ModifiedOn, T1.UserRoleSet_UserId, T1.UserRoleSet_RoleId)
    FROM (
        SELECT 
            T.Id AS UserRoleSet_Id, 
            T.CreatedOn AS UserRoleSet_CreatedOn, 
            T.CreatedBy AS UserRoleSet_CreatedBy, 
            T.SysVersion AS UserRoleSet_SysVersion, 
            T.ModifiedBy AS UserRoleSet_ModifiedBy, 
            T.ModifiedOn AS UserRoleSet_ModifiedOn, 
            T.UserId AS UserRoleSet_UserId, 
            T.RoleId AS UserRoleSet_RoleId, 
            True AS _from0
        FROM DemoEntities.UserRoleSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.UserSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.UserSet", @"
    SELECT VALUE -- Constructing UserSet
        [TelChina.TRF.Demo.DomainModel.User](T1.User_Id, T1.User_Code, T1.User_CreatedOn, T1.User_CreatedBy, T1.User_SysVersion, T1.User_ModifiedBy, T1.User_ModifiedOn, T1.User_Name)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Code AS User_Code, 
            T.CreatedOn AS User_CreatedOn, 
            T.CreatedBy AS User_CreatedBy, 
            T.SysVersion AS User_SysVersion, 
            T.ModifiedBy AS User_ModifiedBy, 
            T.ModifiedOn AS User_ModifiedOn, 
            T.Name AS User_Name, 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.UserSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.RoleSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.RoleSet", @"
    SELECT VALUE -- Constructing RoleSet
        [TelChina.TRF.Demo.DomainModel.Role](T1.Role_Id, T1.Role_Code, T1.Role_CreatedOn, T1.Role_CreatedBy, T1.Role_SysVersion, T1.Role_ModifiedBy, T1.Role_ModifiedOn, T1.Role_Name)
    FROM (
        SELECT 
            T.Id AS Role_Id, 
            T.Code AS Role_Code, 
            T.CreatedOn AS Role_CreatedOn, 
            T.CreatedBy AS Role_CreatedBy, 
            T.SysVersion AS Role_SysVersion, 
            T.ModifiedBy AS Role_ModifiedBy, 
            T.ModifiedOn AS Role_ModifiedOn, 
            T.Name AS Role_Name, 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.RoleSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.UserRoleSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.UserRoleSet", @"
    SELECT VALUE -- Constructing UserRoleSet
        [TelChina.TRF.Demo.DomainModel.UserRole](T1.UserRole_Id, T1.UserRole_CreatedOn, T1.UserRole_CreatedBy, T1.UserRole_SysVersion, T1.UserRole_ModifiedBy, T1.UserRole_ModifiedOn, T1.UserRole_UserId, T1.UserRole_RoleId)
    FROM (
        SELECT 
            T.Id AS UserRole_Id, 
            T.CreatedOn AS UserRole_CreatedOn, 
            T.CreatedBy AS UserRole_CreatedBy, 
            T.SysVersion AS UserRole_SysVersion, 
            T.ModifiedBy AS UserRole_ModifiedBy, 
            T.ModifiedOn AS UserRole_ModifiedOn, 
            T.UserId AS UserRole_UserId, 
            T.RoleId AS UserRole_RoleId, 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.UserRoleSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TelChinaTRFDemoDomainModelStoreContainer.DataTypeTestSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TelChinaTRFDemoDomainModelStoreContainer.DataTypeTestSet", @"
    SELECT VALUE -- Constructing DataTypeTestSet
        [TelChina.TRF.Demo.DomainModel.Store.DataTypeTestSet](T1.DataTypeTestSet_Id, T1.DataTypeTestSet_Property, T1.[DataTypeTestSet.Property_1], T1.[DataTypeTestSet.Property_2], T1.[DataTypeTestSet.Property_3], T1.[DataTypeTestSet.Property_4], T1.[DataTypeTestSet.Property_5], T1.[DataTypeTestSet.Property_6], T1.[DataTypeTestSet.Property_7], T1.[DataTypeTestSet.Property_8], T1.[DataTypeTestSet.Property_9], T1.[DataTypeTestSet.Property_11])
    FROM (
        SELECT 
            T.Id AS DataTypeTestSet_Id, 
            T.Property AS DataTypeTestSet_Property, 
            T.Property_1 AS [DataTypeTestSet.Property_1], 
            T.Property_2 AS [DataTypeTestSet.Property_2], 
            T.Property_3 AS [DataTypeTestSet.Property_3], 
            T.Property_4 AS [DataTypeTestSet.Property_4], 
            T.Property_5 AS [DataTypeTestSet.Property_5], 
            T.Property_6 AS [DataTypeTestSet.Property_6], 
            T.Property_7 AS [DataTypeTestSet.Property_7], 
            T.Property_8 AS [DataTypeTestSet.Property_8], 
            T.Property_9 AS [DataTypeTestSet.Property_9], 
            T.Property_11 AS [DataTypeTestSet.Property_11], 
            True AS _from0
        FROM DemoEntities.DataTypeTestSet AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for DemoEntities.DataTypeTestSet
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("DemoEntities.DataTypeTestSet", @"
    SELECT VALUE -- Constructing DataTypeTestSet
        [TelChina.TRF.Demo.DomainModel.DataTypeTest](T1.DataTypeTest_Id, T1.DataTypeTest_Property, T1.[DataTypeTest.Property_1], T1.[DataTypeTest.Property_2], T1.[DataTypeTest.Property_3], T1.[DataTypeTest.Property_4], T1.[DataTypeTest.Property_5], T1.[DataTypeTest.Property_6], T1.[DataTypeTest.Property_7], T1.[DataTypeTest.Property_8], T1.[DataTypeTest.Property_9], T1.[DataTypeTest.Property_11])
    FROM (
        SELECT 
            T.Id AS DataTypeTest_Id, 
            T.Property AS DataTypeTest_Property, 
            T.Property_1 AS [DataTypeTest.Property_1], 
            T.Property_2 AS [DataTypeTest.Property_2], 
            T.Property_3 AS [DataTypeTest.Property_3], 
            T.Property_4 AS [DataTypeTest.Property_4], 
            T.Property_5 AS [DataTypeTest.Property_5], 
            T.Property_6 AS [DataTypeTest.Property_6], 
            T.Property_7 AS [DataTypeTest.Property_7], 
            T.Property_8 AS [DataTypeTest.Property_8], 
            T.Property_9 AS [DataTypeTest.Property_9], 
            T.Property_11 AS [DataTypeTest.Property_11], 
            True AS _from0
        FROM TelChinaTRFDemoDomainModelStoreContainer.DataTypeTestSet AS T
    ) AS T1");
        }
    }
}


