//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TelChina.TRF.Demo.DomainModel", "OrderOrderLine", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TelChina.TRF.Demo.DomainModel.Model.Order), "OrderLine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TelChina.TRF.Demo.DomainModel.Model.OrderLine), true)]
[assembly: EdmRelationshipAttribute("TelChina.TRF.Demo.DomainModel", "UserUserRole", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TelChina.TRF.Demo.DomainModel.Model.User), "UserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TelChina.TRF.Demo.DomainModel.Model.UserRole), true)]
[assembly: EdmRelationshipAttribute("TelChina.TRF.Demo.DomainModel", "RoleUserRole", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TelChina.TRF.Demo.DomainModel.Model.Role), "UserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TelChina.TRF.Demo.DomainModel.Model.UserRole), true)]
[assembly: EdmRelationshipAttribute("TelChina.TRF.Demo.DomainModel", "MOPick", "MO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TelChina.TRF.Demo.DomainModel.Model.MO), "Pick", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TelChina.TRF.Demo.DomainModel.Model.Pick), true)]

#endregion

namespace TelChina.TRF.Demo.DomainModel.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DemoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DemoEntities object using the connection string found in the 'DemoEntities' section of the application configuration file.
        /// </summary>
        public DemoEntities() : base("name=DemoEntities", "DemoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DemoEntities object.
        /// </summary>
        public DemoEntities(string connectionString) : base(connectionString, "DemoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DemoEntities object.
        /// </summary>
        public DemoEntities(EntityConnection connection) : base(connection, "DemoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SysParam> SysParam
        {
            get
            {
                if ((_SysParam == null))
                {
                    _SysParam = base.CreateObjectSet<SysParam>("SysParam");
                }
                return _SysParam;
            }
        }
        private ObjectSet<SysParam> _SysParam;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> OrderSet
        {
            get
            {
                if ((_OrderSet == null))
                {
                    _OrderSet = base.CreateObjectSet<Order>("OrderSet");
                }
                return _OrderSet;
            }
        }
        private ObjectSet<Order> _OrderSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderLine> OrderLineSet
        {
            get
            {
                if ((_OrderLineSet == null))
                {
                    _OrderLineSet = base.CreateObjectSet<OrderLine>("OrderLineSet");
                }
                return _OrderLineSet;
            }
        }
        private ObjectSet<OrderLine> _OrderLineSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> UserSet
        {
            get
            {
                if ((_UserSet == null))
                {
                    _UserSet = base.CreateObjectSet<User>("UserSet");
                }
                return _UserSet;
            }
        }
        private ObjectSet<User> _UserSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> RoleSet
        {
            get
            {
                if ((_RoleSet == null))
                {
                    _RoleSet = base.CreateObjectSet<Role>("RoleSet");
                }
                return _RoleSet;
            }
        }
        private ObjectSet<Role> _RoleSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserRole> UserRoleSet
        {
            get
            {
                if ((_UserRoleSet == null))
                {
                    _UserRoleSet = base.CreateObjectSet<UserRole>("UserRoleSet");
                }
                return _UserRoleSet;
            }
        }
        private ObjectSet<UserRole> _UserRoleSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataTypeTest> DataTypeTestSet
        {
            get
            {
                if ((_DataTypeTestSet == null))
                {
                    _DataTypeTestSet = base.CreateObjectSet<DataTypeTest>("DataTypeTestSet");
                }
                return _DataTypeTestSet;
            }
        }
        private ObjectSet<DataTypeTest> _DataTypeTestSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pick> PickSet
        {
            get
            {
                if ((_PickSet == null))
                {
                    _PickSet = base.CreateObjectSet<Pick>("PickSet");
                }
                return _PickSet;
            }
        }
        private ObjectSet<Pick> _PickSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SysParam EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSysParam(SysParam sysParam)
        {
            base.AddObject("SysParam", sysParam);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderSet(Order order)
        {
            base.AddObject("OrderSet", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderLineSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderLineSet(OrderLine orderLine)
        {
            base.AddObject("OrderLineSet", orderLine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoleSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoleSet(Role role)
        {
            base.AddObject("RoleSet", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserRoleSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserRoleSet(UserRole userRole)
        {
            base.AddObject("UserRoleSet", userRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataTypeTestSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataTypeTestSet(DataTypeTest dataTypeTest)
        {
            base.AddObject("DataTypeTestSet", dataTypeTest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PickSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPickSet(Pick pick)
        {
            base.AddObject("PickSet", pick);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="DataTypeTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataTypeTest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataTypeTest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="property">Initial value of the Property property.</param>
        /// <param name="property_1">Initial value of the Property_1 property.</param>
        /// <param name="property_2">Initial value of the Property_2 property.</param>
        /// <param name="property_3">Initial value of the Property_3 property.</param>
        /// <param name="property_4">Initial value of the Property_4 property.</param>
        /// <param name="property_5">Initial value of the Property_5 property.</param>
        /// <param name="property_6">Initial value of the Property_6 property.</param>
        /// <param name="property_7">Initial value of the Property_7 property.</param>
        /// <param name="property_8">Initial value of the Property_8 property.</param>
        /// <param name="property_9">Initial value of the Property_9 property.</param>
        /// <param name="property_11">Initial value of the Property_11 property.</param>
        public static DataTypeTest CreateDataTypeTest(global::System.Int32 id, global::System.Byte[] property, global::System.Boolean property_1, global::System.Byte property_2, global::System.DateTime property_3, global::System.DateTimeOffset property_4, global::System.Decimal property_5, global::System.Double property_6, global::System.Guid property_7, global::System.Int16 property_8, global::System.Int64 property_9, global::System.Single property_11)
        {
            DataTypeTest dataTypeTest = new DataTypeTest();
            dataTypeTest.Id = id;
            dataTypeTest.Property = property;
            dataTypeTest.Property_1 = property_1;
            dataTypeTest.Property_2 = property_2;
            dataTypeTest.Property_3 = property_3;
            dataTypeTest.Property_4 = property_4;
            dataTypeTest.Property_5 = property_5;
            dataTypeTest.Property_6 = property_6;
            dataTypeTest.Property_7 = property_7;
            dataTypeTest.Property_8 = property_8;
            dataTypeTest.Property_9 = property_9;
            dataTypeTest.Property_11 = property_11;
            return dataTypeTest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Property
        {
            get
            {
                return StructuralObject.GetValidValue(_Property);
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.Byte[] _Property;
        partial void OnPropertyChanging(global::System.Byte[] value);
        partial void OnPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Property_1
        {
            get
            {
                return _Property_1;
            }
            set
            {
                OnProperty_1Changing(value);
                ReportPropertyChanging("Property_1");
                _Property_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_1");
                OnProperty_1Changed();
            }
        }
        private global::System.Boolean _Property_1;
        partial void OnProperty_1Changing(global::System.Boolean value);
        partial void OnProperty_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Property_2
        {
            get
            {
                return _Property_2;
            }
            set
            {
                OnProperty_2Changing(value);
                ReportPropertyChanging("Property_2");
                _Property_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_2");
                OnProperty_2Changed();
            }
        }
        private global::System.Byte _Property_2;
        partial void OnProperty_2Changing(global::System.Byte value);
        partial void OnProperty_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Property_3
        {
            get
            {
                return _Property_3;
            }
            set
            {
                OnProperty_3Changing(value);
                ReportPropertyChanging("Property_3");
                _Property_3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_3");
                OnProperty_3Changed();
            }
        }
        private global::System.DateTime _Property_3;
        partial void OnProperty_3Changing(global::System.DateTime value);
        partial void OnProperty_3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset Property_4
        {
            get
            {
                return _Property_4;
            }
            set
            {
                OnProperty_4Changing(value);
                ReportPropertyChanging("Property_4");
                _Property_4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_4");
                OnProperty_4Changed();
            }
        }
        private global::System.DateTimeOffset _Property_4;
        partial void OnProperty_4Changing(global::System.DateTimeOffset value);
        partial void OnProperty_4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Property_5
        {
            get
            {
                return _Property_5;
            }
            set
            {
                OnProperty_5Changing(value);
                ReportPropertyChanging("Property_5");
                _Property_5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_5");
                OnProperty_5Changed();
            }
        }
        private global::System.Decimal _Property_5;
        partial void OnProperty_5Changing(global::System.Decimal value);
        partial void OnProperty_5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Property_6
        {
            get
            {
                return _Property_6;
            }
            set
            {
                OnProperty_6Changing(value);
                ReportPropertyChanging("Property_6");
                _Property_6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_6");
                OnProperty_6Changed();
            }
        }
        private global::System.Double _Property_6;
        partial void OnProperty_6Changing(global::System.Double value);
        partial void OnProperty_6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Property_7
        {
            get
            {
                return _Property_7;
            }
            set
            {
                OnProperty_7Changing(value);
                ReportPropertyChanging("Property_7");
                _Property_7 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_7");
                OnProperty_7Changed();
            }
        }
        private global::System.Guid _Property_7;
        partial void OnProperty_7Changing(global::System.Guid value);
        partial void OnProperty_7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Property_8
        {
            get
            {
                return _Property_8;
            }
            set
            {
                OnProperty_8Changing(value);
                ReportPropertyChanging("Property_8");
                _Property_8 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_8");
                OnProperty_8Changed();
            }
        }
        private global::System.Int16 _Property_8;
        partial void OnProperty_8Changing(global::System.Int16 value);
        partial void OnProperty_8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Property_9
        {
            get
            {
                return _Property_9;
            }
            set
            {
                OnProperty_9Changing(value);
                ReportPropertyChanging("Property_9");
                _Property_9 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_9");
                OnProperty_9Changed();
            }
        }
        private global::System.Int64 _Property_9;
        partial void OnProperty_9Changing(global::System.Int64 value);
        partial void OnProperty_9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Property_11
        {
            get
            {
                return _Property_11;
            }
            set
            {
                OnProperty_11Changing(value);
                ReportPropertyChanging("Property_11");
                _Property_11 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Property_11");
                OnProperty_11Changed();
            }
        }
        private global::System.Single _Property_11;
        partial void OnProperty_11Changing(global::System.Single value);
        partial void OnProperty_11Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="MO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MO : Order
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MO object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        /// <param name="product">Initial value of the Product property.</param>
        public static MO CreateMO(global::System.Int64 id, global::System.Int32 sysVersion, global::System.String product)
        {
            MO mO = new MO();
            mO.Id = id;
            mO.SysVersion = sysVersion;
            mO.Product = product;
            return mO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "MOPick", "Pick")]
        public EntityCollection<Pick> Pick
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pick>("TelChina.TRF.Demo.DomainModel.MOPick", "Pick");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pick>("TelChina.TRF.Demo.DomainModel.MOPick", "Pick", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(MO))]
    [KnownTypeAttribute(typeof(SO))]
    public abstract partial class Order : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 订单编号
        /// </summary>
        /// <LongDescription>
        /// 订单的唯一编号,符合相应的编号规则
        /// </LongDescription>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocNo
        {
            get
            {
                return _DocNo;
            }
            set
            {
                OnDocNoChanging(value);
                ReportPropertyChanging("DocNo");
                _DocNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DocNo");
                OnDocNoChanged();
            }
        }
        private global::System.String _DocNo;
        partial void OnDocNoChanging(global::System.String value);
        partial void OnDocNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int32 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int32 value);
        partial void OnSysVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// 订单行
        /// </summary>
        /// <LongDescription>
        /// 订单的明细信息
        /// </LongDescription>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "OrderOrderLine", "OrderLine")]
        public EntityCollection<OrderLine> OrderLine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderLine>("TelChina.TRF.Demo.DomainModel.OrderOrderLine", "OrderLine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderLine>("TelChina.TRF.Demo.DomainModel.OrderOrderLine", "OrderLine", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="OrderLine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderLine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderLine object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="detail">Initial value of the Detail property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="lineNum">Initial value of the LineNum property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        public static OrderLine CreateOrderLine(global::System.Int64 id, global::System.String detail, global::System.Int64 orderId, global::System.Int32 lineNum, global::System.Int64 sysVersion)
        {
            OrderLine orderLine = new OrderLine();
            orderLine.Id = id;
            orderLine.Detail = detail;
            orderLine.OrderId = orderId;
            orderLine.LineNum = lineNum;
            orderLine.SysVersion = sysVersion;
            return orderLine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.Int64 _OrderId;
        partial void OnOrderIdChanging(global::System.Int64 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LineNum
        {
            get
            {
                return _LineNum;
            }
            set
            {
                OnLineNumChanging(value);
                ReportPropertyChanging("LineNum");
                _LineNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LineNum");
                OnLineNumChanged();
            }
        }
        private global::System.Int32 _LineNum;
        partial void OnLineNumChanging(global::System.Int32 value);
        partial void OnLineNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int64 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int64 value);
        partial void OnSysVersionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "OrderOrderLine", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TelChina.TRF.Demo.DomainModel.OrderOrderLine", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TelChina.TRF.Demo.DomainModel.OrderOrderLine", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TelChina.TRF.Demo.DomainModel.OrderOrderLine", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("TelChina.TRF.Demo.DomainModel.OrderOrderLine", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 备料
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="Pick")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pick : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pick object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="mOId">Initial value of the MOId property.</param>
        public static Pick CreatePick(global::System.Int64 id, global::System.Int32 sysVersion, global::System.String name, global::System.Int64 mOId)
        {
            Pick pick = new Pick();
            pick.Id = id;
            pick.SysVersion = sysVersion;
            pick.Name = name;
            pick.MOId = mOId;
            return pick;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int32 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int32 value);
        partial void OnSysVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MOId
        {
            get
            {
                return _MOId;
            }
            set
            {
                OnMOIdChanging(value);
                ReportPropertyChanging("MOId");
                _MOId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MOId");
                OnMOIdChanged();
            }
        }
        private global::System.Int64 _MOId;
        partial void OnMOIdChanging(global::System.Int64 value);
        partial void OnMOIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "MOPick", "MO")]
        public MO MO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MO>("TelChina.TRF.Demo.DomainModel.MOPick", "MO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MO>("TelChina.TRF.Demo.DomainModel.MOPick", "MO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MO> MOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MO>("TelChina.TRF.Demo.DomainModel.MOPick", "MO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MO>("TelChina.TRF.Demo.DomainModel.MOPick", "MO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Role CreateRole(global::System.Int64 id, global::System.Int32 sysVersion, global::System.String name)
        {
            Role role = new Role();
            role.Id = id;
            role.SysVersion = sysVersion;
            role.Name = name;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int32 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int32 value);
        partial void OnSysVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "RoleUserRole", "UserRole")]
        public EntityCollection<UserRole> UserRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserRole>("TelChina.TRF.Demo.DomainModel.RoleUserRole", "UserRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserRole>("TelChina.TRF.Demo.DomainModel.RoleUserRole", "UserRole", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="SO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SO : Order
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SO object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        /// <param name="customer">Initial value of the Customer property.</param>
        public static SO CreateSO(global::System.Int64 id, global::System.Int32 sysVersion, global::System.String customer)
        {
            SO sO = new SO();
            sO.Id = id;
            sO.SysVersion = sysVersion;
            sO.Customer = customer;
            return sO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer
        {
            get
            {
                return _Customer;
            }
            set
            {
                OnCustomerChanging(value);
                ReportPropertyChanging("Customer");
                _Customer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Customer");
                OnCustomerChanged();
            }
        }
        private global::System.String _Customer;
        partial void OnCustomerChanging(global::System.String value);
        partial void OnCustomerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="SysParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysParam : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SysParam object.
        /// </summary>
        /// <param name="sysparamid">Initial value of the sysparamid property.</param>
        /// <param name="sysparamName">Initial value of the sysparamName property.</param>
        /// <param name="sysparamDsc">Initial value of the sysparamDsc property.</param>
        /// <param name="sysparamValue">Initial value of the sysparamValue property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        public static SysParam CreateSysParam(global::System.Int64 sysparamid, global::System.String sysparamName, global::System.String sysparamDsc, global::System.String sysparamValue, global::System.Int32 sysVersion)
        {
            SysParam sysParam = new SysParam();
            sysParam.sysparamid = sysparamid;
            sysParam.sysparamName = sysparamName;
            sysParam.sysparamDsc = sysparamDsc;
            sysParam.sysparamValue = sysparamValue;
            sysParam.SysVersion = sysVersion;
            return sysParam;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 sysparamid
        {
            get
            {
                return _sysparamid;
            }
            set
            {
                if (_sysparamid != value)
                {
                    OnsysparamidChanging(value);
                    ReportPropertyChanging("sysparamid");
                    _sysparamid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sysparamid");
                    OnsysparamidChanged();
                }
            }
        }
        private global::System.Int64 _sysparamid;
        partial void OnsysparamidChanging(global::System.Int64 value);
        partial void OnsysparamidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sysparamName
        {
            get
            {
                return _sysparamName;
            }
            set
            {
                OnsysparamNameChanging(value);
                ReportPropertyChanging("sysparamName");
                _sysparamName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sysparamName");
                OnsysparamNameChanged();
            }
        }
        private global::System.String _sysparamName;
        partial void OnsysparamNameChanging(global::System.String value);
        partial void OnsysparamNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sysparamDsc
        {
            get
            {
                return _sysparamDsc;
            }
            set
            {
                OnsysparamDscChanging(value);
                ReportPropertyChanging("sysparamDsc");
                _sysparamDsc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sysparamDsc");
                OnsysparamDscChanged();
            }
        }
        private global::System.String _sysparamDsc;
        partial void OnsysparamDscChanging(global::System.String value);
        partial void OnsysparamDscChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sysparamValue
        {
            get
            {
                return _sysparamValue;
            }
            set
            {
                OnsysparamValueChanging(value);
                ReportPropertyChanging("sysparamValue");
                _sysparamValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sysparamValue");
                OnsysparamValueChanged();
            }
        }
        private global::System.String _sysparamValue;
        partial void OnsysparamValueChanging(global::System.String value);
        partial void OnsysparamValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int32 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int32 value);
        partial void OnSysVersionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static User CreateUser(global::System.Int64 id, global::System.Int32 sysVersion, global::System.String name)
        {
            User user = new User();
            user.Id = id;
            user.SysVersion = sysVersion;
            user.Name = name;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 代码
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int32 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int32 value);
        partial void OnSysVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// 名称
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// 用户角色
        /// </summary>
        /// <LongDescription>
        /// 用户所分配的所有角色
        /// </LongDescription>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "UserUserRole", "UserRole")]
        public EntityCollection<UserRole> UserRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserRole>("TelChina.TRF.Demo.DomainModel.UserUserRole", "UserRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserRole>("TelChina.TRF.Demo.DomainModel.UserUserRole", "UserRole", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TelChina.TRF.Demo.DomainModel", Name="UserRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserRole object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sysVersion">Initial value of the SysVersion property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        public static UserRole CreateUserRole(global::System.Int64 id, global::System.Int32 sysVersion, global::System.Int64 userId, global::System.Int64 roleId)
        {
            UserRole userRole = new UserRole();
            userRole.Id = id;
            userRole.SysVersion = sysVersion;
            userRole.UserId = userId;
            userRole.RoleId = roleId;
            return userRole;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SysVersion
        {
            get
            {
                return _SysVersion;
            }
            set
            {
                OnSysVersionChanging(value);
                ReportPropertyChanging("SysVersion");
                _SysVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SysVersion");
                OnSysVersionChanged();
            }
        }
        private global::System.Int32 _SysVersion;
        partial void OnSysVersionChanging(global::System.Int32 value);
        partial void OnSysVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int64 _RoleId;
        partial void OnRoleIdChanging(global::System.Int64 value);
        partial void OnRoleIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "UserUserRole", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TelChina.TRF.Demo.DomainModel.UserUserRole", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TelChina.TRF.Demo.DomainModel.UserUserRole", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TelChina.TRF.Demo.DomainModel.UserUserRole", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TelChina.TRF.Demo.DomainModel.UserUserRole", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TelChina.TRF.Demo.DomainModel", "RoleUserRole", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("TelChina.TRF.Demo.DomainModel.RoleUserRole", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("TelChina.TRF.Demo.DomainModel.RoleUserRole", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("TelChina.TRF.Demo.DomainModel.RoleUserRole", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("TelChina.TRF.Demo.DomainModel.RoleUserRole", "Role", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
